- name: PHP sample
  hosts: localhost
  become: yes
  tasks:
    - name: MariaDB server
      ansible.builtin.dnf:
        name: mariadb-server
        state: present
    - name: Install MariaDB
      ansible.builtin.dnf:
        name: mariadb
        state: present
    - name: Install PHP
      ansible.builtin.dnf:
        name: php
        state: present
    - name: Install Composer PHP Depndency Manager
      ansible.builtin.dnf:
        name: composer
        state: present
    - name: Node.js
      ansible.builtin.dnf:
        name: nodejs
        state: present
    - name: npm
      ansible.builtin.dnf:
        name: npm
        state: present
    - name: Start MariaDB
      ansible.builtin.systemd:
        name: mariadb
        enabled: yes
        state: started
    - name: Start httpd
      ansible.builtin.systemd:
        name: httpd
        enabled: yes
        state: started
