- name: PHP 8.2 sample # @see https://tecadmin.net/how-to-install-php-on-centos-9/
  hosts: localhost
  become: yes
  tasks:
    - name: MariaDB server
      ansible.builtin.dnf:
        name: mariadb-server
        state: present
    - name: Install MariaDB
      ansible.builtin.dnf:
        name: mariadb
        state: present
    - name: Install EPEL
      ansible.builtin.dnf:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
        state: present
    - name: Install Remi
      ansible.builtin.dnf:
        name: https://rpms.remirepo.net/enterprise/remi-release-9.rpm
        state: present
        disable_gpg_check: true
    - name: Use PHP Remi 8.2
      command: dnf -y module enable php:remi-8.2
    - name: Use Node.js 18
      command: dnf -y module enable nodejs
    - name: Install PHP
      ansible.builtin.dnf:
        name: php
        state: present
    - name: Install Composer PHP Depndency Manager
      ansible.builtin.dnf:
        name: composer
        state: present
    - name: Node.js
      ansible.builtin.dnf:
        name: nodejs
        state: present
    - name: npm
      ansible.builtin.dnf:
        name: npm
        state: present
    - name: Start MariaDB
      ansible.builtin.systemd:
        name: mariadb
        enabled: yes
        state: started
    - name: Create Laravel Database
      ansible.builtin.shell: mysql </vagrant/laravel-db.sql
